version: "3.8"

services:
  mongodb:
    image: mongo:7.0.2
    container_name: mongodb
    ports:
      - "127.0.0.2:${DB_PORT}:${DB_PORT}"
    volumes:
      - data:/data

  backend:
    build: ./hello_world/toDoList
    ports:
      - "127.0.0.2:${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./client
    container_name: todo_frontend
    ports:
      - "127.0.0.2:${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
volumes:
  data: {}